- Load the dataset

In [2]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [3]:
score_data = pd.read_csv("student_scores.csv")

* Tasks are given below

- Part A: Vector & Matrix Fundamentals
    1. Represent each student's subject scores as a vector.
    2. Compute:
        - Norm-1 and Norm-2 of vectors.
        - Dot product and angle between two students' score vectors.
        - Cross product (for 3D selected subjects).
    3. Find the projection of one vector onto another.

In [4]:
# Represent each student's subject scores as a vector
student_score = score_data.to_numpy()

In [5]:
# Compute norm-1 and norm-2 of vectors

# find the norm-1 (manhattan distance)
np.linalg.norm(student_score, ord=1, axis=1)

# find the norm-2 (euclidean distance)
np.linalg.norm(student_score, ord=2, axis=1)

array([186.39474242, 161.95060975, 156.87893421, 174.49928367,
       175.071414  , 204.435809  , 202.99753693, 181.72506707,
       177.42322283, 155.05160431, 184.52642087, 178.52730884,
       165.54757624, 198.61772328, 174.99714283, 169.78221344,
       181.48278155, 200.76603298, 198.34313701, 170.52858998,
       153.20574402, 167.45447142, 178.71765442, 175.24554203,
       194.94358158, 170.41713529, 171.58962673, 160.98757716,
       151.93748715, 160.85397104, 137.3790377 , 192.40582112,
       203.15019075, 175.10282693, 168.80165876, 168.99408274,
       159.4459156 , 188.53912061, 167.91366829, 195.96428246,
       187.6113003 , 196.36445707, 177.82856913, 172.64993484,
       184.81071398, 191.92706948, 169.97058569, 187.76581158,
       177.79201332, 181.3367034 ])

In [6]:
# Dot product and angle between two students' score vectors.

# pick any two students
student_1 = student_score[0]
student_2 = student_score[1]

# perform the dot product
dot_product = np.dot(student_1, student_2)

# multiply the distance of both vectors
student_1_distance = np.linalg.norm(student_1, ord=2)
student_2_distance = np.linalg.norm(student_2, ord=2)
multiplied_distance = student_1_distance * student_2_distance

# find the angle
ang_radians = np.arccos(dot_product / multiplied_distance)

# convert radians to degree
ang_degree = np.degrees(ang_radians)

print(f"Dot product of two students score is {dot_product}")
print(f"Angle between two students score is {ang_degree}")

Dot product of two students score is 28366
Angle between two students score is 20.001436612321907


In [7]:
# Cross product (for 3D selected subjects).

# pick any two students
student_1 = student_score[0,:3]
student_2 = student_score[1,:3]

# perform the cross product
cross_product = np.cross(student_1, student_2)

print(f"Cross Product of two student's three subject is {cross_product}")

Cross Product of two student's three subject is [ 1530  3705 -5460]


In [8]:
# Find the projection of one vector onto another.

# pick any two students
student_1 = student_score[0]
student_2 = student_score[1]

# find the dot product
dot_product = np.dot(student_1, student_2)

# find the euclidean distance of student_2
distance = np.linalg.norm(student_2, ord=2)
distance_sqr = distance**2

# find the projection of student 1 on student 2
projection_of_1_on_2 = (dot_product / distance_sqr) * student_2

print(f"Projection of student 1 on student 2 is {projection_of_1_on_2}")

Projection of student 1 on student 2 is [98.41795028 45.42366936 58.40186061 55.1573128  81.11369529 76.78763154]


- Part B: Matrix Operations
    - Form a matrix of students x subjects. Perform:
    - Matrix addition and multiplication.
    - Transpose and Inverse (if possible).
    - Determinant.

In [9]:
# matrix addition and multiplication

# form a matrix
matrix_1 = np.vstack([student_score[0]])
matrix_2 = np.vstack([student_score[1]])

# perform the addition
matrix_add = matrix_1 + matrix_2

# perform the multiplication
matrix_multiply = matrix_1 @ matrix_2.T

print(f"Matrix addition is {matrix_add}")
print(f"Matrix multiplication is {matrix_multiply}")

Matrix addition is [[169 138 141  98 143 142]]
Matrix multiplication is [[28366]]


In [10]:
# Transpose and Inverse of matrix.

# matrix transpose
matrix_1_transpose = matrix_1.T
matrix_2_transpose = matrix_2.T

print(f"Shape of Matrix 1 is {matrix_1.shape}")
print(f"Shape of Matrix 1 transpose is {matrix_1_transpose.shape}")

# matrix inverse and determinant is perform on only square matrix

Shape of Matrix 1 is (1, 6)
Shape of Matrix 1 transpose is (6, 1)


- Part C: Linear Transformations & Geometry
    - Explain line, plane, and hyperplane with respect to your dataset dimensions.
    - Show how dimensionality increases from 2D → 3D → higher dimensions with
hyperplanes.

- Part D: Eigenvalues & Decomposition
    - Compute the eigenvalues and eigenvectors of the covariance matrix.
    - Perform LU Decomposition of the dataset matrix.
    - Perform Singular Value Decomposition (SVD) and explain its role in dimensionality
reduction.

In [11]:
# Compute the eigenvalues and eigenvectors of the covariance matrix.

# form a covariance matrix
covariance_matrix = np.cov(student_score, rowvar=False)

# find the eigen_values and eigen_vectors
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

print("Covariance matrix are given below")
for i in covariance_matrix:
    print(i)
    
print("\n\nEigen Values are given below")
for i in eigen_values:
    print(i)

print("\n\nEigen Vectors are given below")
for i in eigen_vectors:
    print(i)

Covariance matrix are given below
[313.96938776 -98.82653061 -90.50204082 -13.55714286 -92.04897959
 -25.65918367]
[-98.82653061 363.7244898  -15.11836735   8.63469388 -33.98367347
 -43.03877551]
[-90.50204082 -15.11836735 339.03836735  49.09877551  58.19020408
  24.1844898 ]
[-13.55714286   8.63469388  49.09877551 265.78816327 -50.69877551
  19.06571429]
[-92.04897959 -33.98367347  58.19020408 -50.69877551 312.58122449
  56.92979592]
[-25.65918367 -43.03877551  24.1844898   19.06571429  56.92979592
 372.7922449 ]


Eigen Values are given below
512.2571102017771
444.6314022965339
158.96603021607103
194.59564898061268
334.39350129169145
323.0501845643329


Eigen Vectors are given below
[ 0.57594885 -0.33997574 -0.6819094  -0.27525469  0.10902397 -0.00690081]
[-0.1151119   0.77237196 -0.41467572 -0.22121835 -0.11044517  0.39635736]
[-0.52563894 -0.01454701 -0.14091699 -0.52779825  0.49033954 -0.42968667]
[-0.06884425  0.06477272 -0.24355943  0.65089861  0.69550083  0.15605566]
[-0.487060

In [12]:
# Perform LU Decomposition of the dataset matrix.

# derive the squeare matrix from the given dataset matrix
score_square_matrix = student_score[:6,:]

# perform LU decomposition on square matrix
permutation_matrix, lower_triangular_matrix, upper_triangular_matrix = sp.linalg.lu(score_square_matrix)

print(f"Permutation matrix is given below")
for i in permutation_matrix:
    for j in i:
        print(j, end="  ")
    print()
print("\n\nLower Triangular matrix is given below")
for i in lower_triangular_matrix:
    for j in i:
        print(round(j,2), end="  ")
    print()
    
print(f"\n\nUpper Triangular matrix is given below")
for i in upper_triangular_matrix:
    for j in i:
        print(round(j,2), end="  ")
    print()

Permutation matrix is given below
0.0  0.0  0.0  1.0  0.0  0.0  
1.0  0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  1.0  
0.0  1.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  1.0  0.0  
0.0  0.0  1.0  0.0  0.0  0.0  


Lower Triangular matrix is given below
1.0  0.0  0.0  0.0  0.0  0.0  
0.59  1.0  0.0  0.0  0.0  0.0  
0.52  0.59  1.0  0.0  0.0  0.0  
0.86  0.92  0.36  1.0  0.0  0.0  
0.9  0.13  0.18  -0.55  1.0  0.0  
0.75  0.69  -0.13  -0.23  0.47  1.0  


Upper Triangular matrix is given below
91.0  42.0  54.0  51.0  75.0  71.0  
0.0  65.08  20.96  41.74  26.49  37.87  
0.0  0.0  58.77  43.09  43.67  29.04  
0.0  0.0  0.0  -50.88  -36.61  -35.34  
0.0  0.0  0.0  0.0  -52.98  -2.44  
0.0  0.0  0.0  0.0  0.0  -19.34  


In [13]:
# Perform Singular Value Decomposition (SVD) and explain its role in dimensionality reduction.

# perform SVD
U, S, V_t = np.linalg.svd(student_score, full_matrices=False)

print(f"U matrix (left singular vectors) shape: {U.shape}")
print(f"S (singular values): {S}")
print(f"V_t matrix (right singular vectors) shape: {V_t.shape}")


# Role of SVD in Dimensionality Reduction:

# SVD breaks data into parts. By keeping only the most important parts (components), we reduce the number of features while keeping most of the information. This makes the data simpler and easier to work with.

U matrix (left singular vectors) shape: (50, 6)
S (singular values): [1224.91073493  151.73864988  146.51408238  126.93114186  119.9449311
   97.5315127 ]
V_t matrix (right singular vectors) shape: (6, 6)


- Part E: Dimensionality Reduction
    - Apply Principal Component Analysis (PCA) to reduce the dataset from multiple
    subjects to 2 dimensions.
    - Apply Linear Discriminant Analysis (LDA) to classify students into "Above Average"
    and "Below Average" categories.

In [14]:
# Apply Principal Component Analysis (PCA) to reduce the dataset from multiple subjects to 2 dimensions.

# standardize the data
scaler = StandardScaler()
standard_data = scaler.fit_transform(student_score)

# apply PCA to reduce 2 dimensions
pca = PCA(n_components = 2)
standard_pca = pca.fit_transform(standard_data)

# Display the first two principal components for each student
print("PCA - 2D projection of the data:")
print(standard_pca[:, :])

PCA - 2D projection of the data:
[[-3.15059462e-01  6.09925767e-01]
 [ 1.23379652e+00 -1.72543461e+00]
 [ 1.04668421e+00  1.03697341e+00]
 [-5.08567278e-01  9.85749599e-01]
 [ 1.06082203e+00 -4.85779096e-01]
 [-2.81357702e+00 -3.21564326e-01]
 [-3.84473649e-01 -2.10373992e+00]
 [-8.36655317e-01  1.54772555e-01]
 [ 3.32050291e-01 -7.02506977e-01]
 [ 2.58042658e+00 -1.44604040e-01]
 [-1.34943686e+00  1.21932395e-02]
 [-2.60844501e-01  1.85879934e+00]
 [-1.43404195e+00 -2.60487722e-01]
 [-2.42227543e+00  2.89725659e-01]
 [ 2.87387477e-01  1.81737837e+00]
 [ 9.63294657e-01 -1.90280230e+00]
 [ 8.74476019e-03 -4.75217278e-01]
 [-9.41145855e-01  9.97413372e-01]
 [-1.77490425e+00 -1.32388447e+00]
 [-1.65773213e+00 -1.84236080e-01]
 [-2.02744543e-01  3.36935709e-01]
 [ 1.43032461e+00  9.07221256e-01]
 [-1.89636414e+00  6.96103174e-01]
 [-7.17512393e-01 -1.73222654e+00]
 [-1.87084700e-02  1.16677972e+00]
 [ 6.57990289e-01  9.66413545e-01]
 [ 2.12399659e-01 -8.38203529e-01]
 [-6.34006149e-01  1.0

In [15]:
# Apply Linear Discriminant Analysis (LDA) to classify students into "Above Average" and "Below Average" categories.

# Create a "class" label for each student based on average score
average_score = np.mean(student_score, axis=1)
threshold = np.median(average_score)  # Set threshold as the median score

# Classify as Above Average (1) or Below Average (0)
y = np.where(average_score > threshold, 1, 0)

# Apply LDA
lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(standard_data, y)

# Display the LDA transformed data 
print("LDA - Student classification into Above Average/Below Average (first 5 students):")
print(X_lda[:, :])

# Display the class labels
print("\nClass labels (Above Average: 1, Below Average: 0):")
print(y[:])

LDA - Student classification into Above Average/Below Average (first 5 students):
[[ 1.01497461]
 [-2.41672392]
 [-1.4606314 ]
 [ 0.34963576]
 [-0.2802423 ]
 [ 2.76782846]
 [ 1.93479526]
 [ 0.6166004 ]
 [ 0.23833247]
 [-2.70096608]
 [ 1.15850035]
 [ 0.781549  ]
 [-2.06625806]
 [ 2.36401925]
 [ 0.52096108]
 [-1.91215476]
 [ 0.77609235]
 [ 3.1088813 ]
 [ 1.6440421 ]
 [-1.64531231]
 [-3.10490202]
 [-1.58928474]
 [-0.41772584]
 [-0.9060782 ]
 [ 2.93953513]
 [-0.52405809]
 [-0.51101953]
 [-1.40965714]
 [-3.1510444 ]
 [-2.30811643]
 [-4.3231869 ]
 [ 1.46710897]
 [ 3.44585278]
 [ 0.76818428]
 [-1.85159506]
 [-1.2786202 ]
 [-1.96762955]
 [ 1.75989823]
 [-0.24854647]
 [ 1.86426522]
 [ 2.15791746]
 [ 2.06651085]
 [-1.07565482]
 [-0.46535622]
 [ 1.41046829]
 [ 1.58185578]
 [-0.86333237]
 [ 1.82886724]
 [-0.76377234]
 [ 0.6751925 ]]

Class labels (Above Average: 1, Below Average: 0):
[1 0 0 1 0 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0
 1 0 1 1 1 0 0 1 1 0 1 0 1]
